#include "lmic.h"
#include "hal.h"
#include "main.h" // Gives access to GPIOC, GPIO_PIN_5, and HAL commands

// Reference the global SPI handle generated by CubeMX for SPI2
extern SPI_HandleTypeDef hspi2; 

// 1. Initialize the SPI Peripherals (Handled automatically by main.c's MX_SPI2_Init)
void hal_spi_init (void) {
    // Leave blank because STM32CubeMX already initializes hspi2 during boot.
}

// 2. Drive the NSS Pin LOW to select the RFM95W transceiver
void hal_spi_select (u1_t on) {
    if (on) {
        // Assert Chip Select: Pull PC5 LOW
        HAL_GPIO_WritePin(GPIOC, GPIO_PIN_5, GPIO_PIN_RESET);
    } else {
        // Deassert Chip Select: Pull PC5 HIGH
        HAL_GPIO_WritePin(GPIOC, GPIO_PIN_5, GPIO_PIN_SET);
    }
}

// 3. Synchronously write a byte and read a byte back over SPI2
u1_t hal_spi_write (u1_t outval) {
    u1_t inval = 0;

    // Full-duplex 1-byte block transfer with a 10ms safety timeout
    HAL_SPI_TransmitReceive(&hspi2, &outval, &inval, 1, 10);

    return inval; // Return the response byte from the RFM95W register
}

// ============================================================================
// Existing Required Stubs
// ============================================================================

void lmic_hal_pin_rxtx (u1_t val) {
    (void)val; // Adafruit breakout board switches RF paths internally via hardware
}

bit_t lmic_hal_queryUsingTcxo (void) {
    return 0; // Uses a standard crystal, not a TCXO
}

s1_t lmic_hal_getRssiCal (void) {
    return 0; // Default calibration factor
}

